### ISSUE TITLE
Dependency on Exexif

### ISSUE THREAD

**Issue by atavistock** [amotion-city/lib_lat_lon#6]
There appears to be a dependency on Exexif which is not declared in mix.exs (well it is but only under the `:ci` group)

Specifically
```
== Compilation error in file lib/lib_lat_lon/data/coords.ex ==
** (ArgumentError) could not load module Exexif due to reason :unavailable
    lib/lib_lat_lon/data/coords.ex:26: (module)
```

**Comment by am-kantox** [comment]
Hi @atavistock, thanks for pointing this out.

There were some requests to amend the original `exexif` package, I provided the PR which has not been merged, so some people asked me to fork it and I did `nextexif`. Both might be used here, so one just needs to explicitly define a dependency.

I should have it clearly stated in docs and I will one day.
