### ISSUE TITLE
I cannot compile

### ISSUE THREAD

**Issue by ehayun** [amotion-city/lib_lat_lon#7]
I am getting this

```
mix deps.compile lib_lat_lon --force
==> lib_lat_lon
Compiling 10 files (.ex)

== Compilation error in file lib/lib_lat_lon/data/coords.ex ==
** (ArgumentError) could not load module Exexif due to reason :unavailable
    lib/lib_lat_lon/data/coords.ex:26: (module)
```

What do I do?

**Comment by am-kantox** [comment]
Hi @ehayun, thanks for reporting.

The docs were not clear on the topic, to use the library you have to explicitly specify `exexif` library to use as described here: https://hexdocs.pm/lib_lat_lon/intro.html#installation

Basically, this would do
```elixir
def deps do
  [
    {:lib_lat_lon, "~> 0.1"},
    # Use PragDave’s exexif
    {:exexif, "~> 0.0"},
    …
  ]
end
```

**Comment by ehayun** [comment]
Yes, I did that and still not find

**Comment by ehayun** [comment]
look:
```
case Code.ensure_compiled(Exexif) do
    {:module, Exexif} ->
      :ok

    {:error, reason} ->
      raise ArgumentError,
            "could not load module #{inspect(Exexif)} due to reason #{inspect(reason)}"
  end
```
You are using it but I have this error
here is a part of my mix.exs file
```
{:calendar, "~> 1.0"},
      {:lib_lat_lon, "~> 0.7"},
      {:exexif, "~> 0.0"},
      {:phone, "~> 0.5.2"},
```

**Comment by am-kantox** [comment]
Eh. Would not `rm -rf _build && mix compile` help?

I am to reopen it until resolved. Maybe for modern Elixir with smart dependency resolution we’d need more aggressive check.

**Comment by ehayun** [comment]
No, I did that already

**Comment by am-kantox** [comment]
It’s all weird, I finally managed to reproduce it and moved the setting into `config`, defaulted to `:exexif`, so under normal circumstances, you should be good by including `:lib_lat_lon` only.

> Package published to https://hex.pm/packages/lib_lat_lon/0.8.0
> (9721a8c7b3fc880c59087f1484b6120d101804ab15a73de5e776528ff3ad200d)

**Comment by ehayun** [comment]
Great. Now it is working fine
